public class Test_emailDetailahandler {
   /* static testMethod void myUnitTest() {
        Detail__c dummyDetail=new Detail__c();
        dummyDetail.Body__c = 'parachute';
        dummyDetail.Subject__c = 'test subject';
        test.StartTest();
        Test.setMock(HttpCalloutMock.class, new  Test_FutureCallout());
        insert dummyDetail ;
        test.StopTest();
        Detail__c dummyDetail1=[Select id
                                    ,Body__c
                                    ,Subject__c
                              FROM Detail__c 
                              where  Body__c='parachute'];
            } */
            
}